name = "www-notion"
main = "src/index.ts"
compatibility_date = "2024-01-08"
workers_dev = true

routes = [
	{ pattern = "tuscanywildnature.xyz", custom_domain = true },
	{ pattern = "www.tuscanywildnature.xyz", custom_domain = true }
]
